server:
  port: 8861
  servlet:
    context-path: /service

spring:
  application:
    # 指定注册到Eureka Server上的应用名称
    name: lp-service

eureka:
  client:
    service-url:
      # 注册地址
      defaultZone: http://localhost:8761/eureka/eureka/
  instance:
    # 将自己的IP注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server
    prefer-ip-address: true