server:
  # 项目端口号
  port: 8871

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/actual-combat?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: myPassword
    # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver

#整合mybatis
mybatis:
  type-aliases-package: com.entity
  mapper-locations: classpath:mapper/*Mapper.xml

#mappers 多个接口时逗号隔开
mapper:
  mappers:
    - com.lp.dao.MyMapper
  notEmpty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql