server:
  port: 8868

spring:
  application:
    # 指定注册到Eureka Server上的应用名称
    name: lp-stream-server
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.88.128
                port: 5672
                username: admin
                password: mypassword
      bindings:
        #队列
        test_output:
          #消息类型
          content-type: application/json
          #消息队列目标
          destination: default.messages
          #与MQ绑定标志
          binder: rabbit
          #分组，如果是点对点的话，需要指定，广播模式则不用
          group: group_name

eureka:
  client:
    service-url:
      # 注册地址
      defaultZone: http://localhost:8761/eureka
  instance:
    # 将自己的IP注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server
    prefer-ip-address: true