server:
  # 项目端口号
  port: 8871

spring:
  elasticsearch:
    rest:
      # 是否启用es
      enable: false
      host: 192.168.137.114
      port: 9200
    uris: 192.168.137.114:9200
    username: elastic
    password: MMEsEUHm*RnjjLZ__XIp
  mvc:
    servlet:
      load-on-startup: 1
