server:
  port: 8870

spring:
  application:
    # 指定注册到Eureka Server上的应用名称
    name: lp-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        # 路由标识（id：标识，具有唯一性）   简单尝试
        - id: lp-feign-hystrix
          # 目标服务地址（uri：地址，请求转发后的地址）
          uri: lb://lp-feign-hystrix
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
            ## 转发地址格式为 uri/archive
            - Path=/hystrix/**
          filters:
            - StripPrefix=1
        # 路由标识（id：标识，具有唯一性）   简单尝试
        - id: lp-feign
          # 目标服务地址（uri：地址，请求转发后的地址）
          uri: lb://lp-feign
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
            ## 转发地址格式为 uri/archive
            - Path=/feign/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      # 注册地址
      defaultZone: http://localhost:8761/eureka
  instance:
    # 将自己的IP注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server
    prefer-ip-address: true