server:
  port: 8866

spring:
  application:
    # 指定注册到Eureka Server上的应用名称
    name: lp-feign-hystrix

eureka:
  client:
    service-url:
      # 注册地址
      defaultZone: http://localhost:8761/eureka
  instance:
    # 将自己的IP注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server
    prefer-ip-address: true

#开启hystir
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #hystrix超时时间
            timeoutInMilliseconds: 3000