#开启hystir
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #hystrix超时时间