server:
  port: 8871
  servlet:
    context-path: /user

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1/actual-combat?useUnicode=true&useSSL=false
    username: root
    password: MyNewPass4!
    # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus 配置
mybatis-plus:
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      table-underline: true
      db-type: mysql
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  #xml文件地址
  mapper-locations: classpath*:mapper/**/*.xml