server:
  port: 8864

spring:
  application:
    # 指定注册到Eureka Server上的应用名称
    name: config-server
  cloud:
    #config配置
    config:
      server:
        git:
          uri: https://gitee.com/liupan1230/spring-series.git
          #          username:
          #          password:
          default-label: master
          search-paths: config

eureka:
  client:
    service-url:
      # 注册地址
      defaultZone: http://localhost:8761/eureka
  instance:
    # 将自己的IP注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server
    prefer-ip-address: true
